pioneers/website

_sass/_base.scss, _sass/_styles.scss, about/about-us.html, get-involved/become-mentor.html, get-involved/become-mentor.md
Also cleaned up the SCSS a bit and started implementing the Become a Mentor page.
=> Implemented RC descriptions on About page using Flexbox.

about/about-us.html
Added some verbage about our nonprofit status in our About Us page
=> Modified About Us to include a blurb about Mike from Fish

_includes/annual-data.html, _sass/_styles.scss
Bar graph is standard display; annual data is now displayed as a simple table on small screen sizes.
=> Closes Issue #86

404.html
=> Close #139

docker-build.sh, programs/scholarship.md
* Remove button and add date when app will be launched
* Add a type to the bash script for easier execution
=> Scholarship page changes

README.md
Added instructions/precautions regarding
- robots.txt
- changing base settings in `_config.yml`
=> Added some dev instructions to README

_config.yml
Also remove the unnecessary br.
=> config: Update copyright to 2016

programs/scholarship.md
Will also need to add a blurb, preferably on the homepage, but not sure what sort of styling we have available for that.
=> Update scholarship deadline

_posts/2016-5-1-scholarship-winners.markdown
=> Add image to post instead of using default template layout

404.html
Hackily redirect via Javascript in 404.html
=> Close #203, #171

programs/scholarship.md
=> Commented out 2016 scholarship stuff and replaced with a stopgap blurb

get-involved/join-staff.md
Update Robotics@Berkeley links with links to their new website
=> Fix outdated Robotics@Berkeley links

.gitignore, docker-dev.sh
* Add .swp to gitignore
* Add magic bash header and mark executable docker-dev.sh
=> Add to gitignore and make dev script executable

_sass/_styles.scss
=> Fix gallery heading images

get-involved/join-staff.md
=> Add open in new tab link for infographic

_sass/_styles.scss, about/foundation.md, get-involved/volunteer.html, programs/scholarship.md, support-pie/donate.html
=> Change the color of all gold links back to blue

_sass/_styles.scss, index.html
The padding on the announcement box bugged me :P
=> Cleaned up announcement container styles

get-involved/forms.html, support-pie/donate.html
=> Minor URL changes on Staff Forms page and Donate page

programs/scholarship.md
=> Added past scholarship winners to scholarship page

_data/project-managers.yml
=> Add seiya to pie team page

support-pie/donate.html
=> donate: Fix minor HTML issues and typos

compete/rc-fall.html, compete/rc-spring.html, get-involved/faq.html, index.html, staffonly/index.html, support-pie/sponsors.html
These changes do not modify the functionality of the site.
=> Fix HTML validity for <hr>, <br>, and &amp;

_layouts/default-minus-hero.html, _layouts/default.html
=> default.html: Add lang="en" to <html>

compete/gcal.html, compete/rc-spring.html
=> RC Comp page: timeline small screen fix, gcal moved, added back facts

_sass/_styles.scss
Seems to make the text more readable.
=> _styles: Make the fade overlay slightly darker

_layouts/api.html, _layouts/software.html, _sass/_styles.scss, _sass/_syntax-highlighting.scss, assets/student-resources/quickstart.py, software/actions.md, software/auto.md, software/dawn.md, software/index.html, software/robot_api.md, software/teleop.md
Ticks is missing a definition @JHGZhou
=> Add Glossary

_sass/_styles.scss, programs/fall-workshops.md
Referencing this doc https://docs.google.com/document/d/1j2l-RHxzLg7wJ_b9xPTqXun5TNnxsrBcmD2npFrzH0w/edit
Should I move "Questions?" to the very bottom?
=> PiE On the Road page built, initial styling, forms coming soon

_data/projects.yml
- Used @tingtingchiang 's tagline from Project Expo
=> Update the Hibike/Runtime tagline

_includes/header.html
=> DeCal typo

_layouts/main.html, compete/rc-spring.html, index.html
1. Changed banner to "2018 Spring Competition Application is now open"
2. Attached link for application to the banner
3. Changed all the dates and time in the Kickoff, Design Review, Scrimmage, and Final competition to TBD, please update once time and location are known
4. commented out lines for Student Registration Form, View map of event locations, and View PDF of event itinerary
Changes made in the homepage:
1. Removed the Join Us button
2. added Spring 2018 Competition announcements and linked it to compete --> PiE Robotics Competition
modified:   _layouts/main.html
modified:   compete/rc-spring.html
modified:   index.html
=> Worksession Oct 26, 2017

_sass/_styles.scss, index.html
- also removed old sections on homepage (3 column thing, statistics, schedule)
=> added support us on main page

software/robot_api.md
Old fix from quite a while ago
=> Add dash to x-axis

software/index.html
to support: Dawn Displays Special Values for Game (#551)
=> Update dawn links to v2018.1.0

software/index.html, software/quickstart.md
Adjust the template starter code for students in quickstart
Incentivize learning more about the code to make your bot better by lowering the quality of the given code.
=> Nerf the code those whomst copy

software/robot_api.md
- ensure use of IDs rather than custom names
- remove the team flag functionality
- correct example usage of THE MOST IMPORTANT SENSOR
- clarify yogi documentation for primary use case
=> Update the API for 2018

programs/scholarship.md
Link: http://linode.matthewchang.com/programs/scholarship
Updated the due date for scholarship app.
**Note**: Please do not merge and immediately deploy. If possible, can I get approval so that I may coordinate with @dwai213 on the messaging to the teams.
=> Update due date for scholarship

programs/scholarship.md
Simple update with an extra alert div.
=> Update Scholarship deadline to April 23rd

software/index.html
=> Revert "Software Release "dawn/2.0.0-2019-05-04T105043""

.travis.yml, Gemfile, Gemfile.lock
- wew there's a green checkmark again
- Specify ruby version as used in Dockerfile
- Update Jekyll version
- Update bundler version to stop breaking stuff
=> Fix Travis

get-involved/index.html
Duplicated the link to the cognito forms because it was honestly way too hard to find for a dumb dumb like me.
Also capitalized the "R" in "Recruiting" because it bothered me.
=> Easy Join Now

get-involved/index.html
Updated link to infosession slides to 2019 version. Do not push until slides completed by Kirsten.
=> Updated infosession slides

get-involved/index.html
Added Facebook event links to schedule of events.
=> Facebook event links

compete/rc-fall.html
fixed rsvp forms for fall comp
=> updated rc fall

_data/gallery-fa-comp-2015.yaml, _data/gallery-fa-events-2013.yaml, _data/gallery-fa-events-2014.yaml, _data/gallery-retreat-2013.yaml, _data/gallery-retreat-2015.yaml, _data/gallery-sp-comp-2015.yaml, _data/gallery-sp-events-2013.yaml, _data/gallery-sp-events-2016.yaml, _data/gallery-staff-events-2016.yaml, _data/leadership.yml, _data/project-managers.yml, _data/projects.yml, _data/staff-bio.yaml, about/index.html, gallery/index.html
(from previous pull requests)
Updated Staff Bios
Updated Project PMs / Descriptions
Cleaned up Gallery code
=> Update bio gall proj

_data/gallery-fa-comp-2015.yaml, _data/gallery-fa-events-2013.yaml, _data/gallery-fa-events-2014.yaml, _data/gallery-retreat-2013.yaml, _data/gallery-retreat-2015.yaml, _data/gallery-sp-comp-2015.yaml, _data/gallery-sp-events-2013.yaml, _data/gallery-sp-events-2016.yaml, _data/gallery-staff-events-2016.yaml, _data/leadership.yml, _data/project-managers.yml, _data/projects.yml, _data/staff-bio.yaml, about/index.html, gallery/index.html
only the ones who filled out the form get to be on the website lol
=> Update staff bios

_includes/header.html, compete/rc-spring.html
updated the stuff jeanney mentioned on slack
=> fixed links and spring rc dates

get-involved/become-mentor.md
Changed from "Jan 30, Friday 6:30 - 7:30" to "Jan 30, Thursday 6:30 - 7:30". Emphasis on Friday -> Thursday
=> Mentor Infosession date

kit/index.md
=> Update Kit Extension Catalog

programs/scholarship.md
* Removed stale notification
* Cleaned up schedule, which will be updated in future commit
* Removed link to scholarship webapp login
* Add 2019 winner
=> Update Scholarship page

programs/scholarship.md
- 2020 will be the seventh iteration of the scholarship (2014 start)
- Copy the schedule from the powerpoint on to the web page
- Update resources for 2020
=> Update for 2020 season

programs/scholarship.md
- Per the [last scholarship meeting](https://docs.google.com/document/d/1h7D6baNsk2JoszEuUbeYcJEFr-jJNz4I6UFTDOQwiMc/edit), the interviews with finalists may or may not all be during the previous final comp day
- Reflect this on the website
=> Clarify that interview date is up in the air

programs/scholarship.md
- Allow students to sign themselves up for the email group
=> Add the email group sign up to the website

README.md
- Remove cruft from the README
- remove personal gh-pages section
- Point more prominently to the wiki for getting started
=> Clean up the README.md

about/index.html
- Foundation has a new address
- Update it
=> Update the legal address of Foundation

security.txt
* Adds a security.txt file to the root directory to follow upcoming
security best practice.
=> Add security.txt file to website

software/index.html
Update Dawn download links and link to Robot API
=> New Software Links

.github/workflows/push-staging.yml
* Rename Action for clarity
* Set Action environment name to pick up correct secrets context
=> Specify environment in deploy staging Action
